import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import PrelineScript from "@/components/PrelineScript";
import { NextIntlClientProvider } from "next-intl";
import { getLangDir } from "rtl-detect";
import { TooltipProvider } from "@/components/ui/tooltip";
import StoreProvider from "@/features/StoreProvider/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = ["en", "ru"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  const direction = getLangDir(locale);

  return (
    <html lang={locale} dir={direction}>
      <NextIntlClientProvider messages={messages}>
        <StoreProvider>
          <TooltipProvider>
            <body>{children}</body>
          </TooltipProvider>
        </StoreProvider>
      </NextIntlClientProvider>
      <PrelineScript />
    </html>
  );
}
